site_name: Странице предмета
site_url: https://radlovacki.github.io/lessons/
site_author: Велимир Радловачки
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Dark mode
  favicon: images/icon.svg
  icon:
    logo: fontawesome/solid/graduation-cap
  language: sr
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
copyright: Copyright &copy; 2025 Velimir Radlovački

nav:
  - Почетна: index.md
  - Prog1:
    - Увод:
      - Програмски језици: prog_1/01/index.md
      - Поделе програмских језика: prog_1/01/podele.md
  - Prog2:
    - Поглавље 1:
      - Лекција 1: prog_2/01/index.md
  - Prog3:
    - Поглавље 1:
      - Лекција 1: prog_3/01/index.md
  - Prog4:
    - Поглавље 1:
      - Лекција 1: prog_4/01/index.md
  - CS:
    - Поглавље 1:
      - Лекција 1: rii/01/index.md
  - WebDes:
    - Увод у веб дизајн:
      - Увод: webd/01/index.md
  - WebDev3:
    - Поглавље 1:
      - Лекција 1: webp_3/01/index.md
  - WebDev4:
    - Поглавље 1:
      - Лекција 1: webp_4/01/index.md

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - glightbox

hooks:
  - hooks/socialmedia.py

extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/radlovacki
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/velimirradlovacki/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/velimir.radlovacki
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/radlovacki/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/VelimirRadlovački
    - icon: fontawesome/brands/twitter
      link: https://x.com/radlovacki
  generator: false

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6