site_name: Странице предмета
site_url: https://radlovacki.github.io/lessons/
site_author: Велимир Радловачки
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Dark mode
  icon:
    logo: fontawesome/solid/graduation-cap
  language: sr
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
copyright: Copyright &copy; 2025 Velimir Radlovački

nav:
  - Почетна: index.md
  - Computer Science:
    - Добродошли: compsci/index.md
    - Рачунарство:
      - Увод у рачунарство и информатику: compsci/01/01_uvod.md
      - Инсторијат развоја рачунара: compsci/01/02_istorijat.md
      - Генерације електронских рачунара: compsci/01/03_generacije.md
      - Рачунарски систем: compsci/01/04_racunarski_sistem.md
      - Кућиште и напајање: compsci/01/05_kuciste.md
      - Матична плоча: compsci/01/06_maticna.md
      - Припрема за први тест: compsci/01/07_test_1.md
      - Процесор: compsci/01/08_procesor.md
      - Меморије: compsci/01/09_memorije.md
      - Представљање података у меморији: compsci/01/10_podaci.md
  - Programming 1:
    - Добродошли: prog1/index.md
    - Увод:
      - Програмски језици: prog1/01/index.md
      - Поделе програмских језика: prog1/01/podele.md
  - Programming 3:
    - Добродошли: prog3/index.md
    - Основни концепти објектно-оријентисаног програмирања:
      - Увод: prog3/01/01_uvod.md
      - Класа и објекат: prog3/01/02_klasa_objekat.md
      - Чланови класе: prog3/01/03_clanovi_klase.md
      - Енкапсулација: prog3/01/04_enkapsulacija.md
      - Наслеђивање: prog3/01/05_nasledjivanje.md
      - Полиморфизам: prog3/01/06_polimorfizam.md
    - Програмски језик C#:
      - Увод: prog3/02/01_uvod.md
      - Припрема окружења и израда пројекта: prog3/02/02_okruzenje.md
      - Метода Main, класа Program и именски простори: prog3/02/03_main.md
      - Читање и испис података: prog3/02/04_citanje_ispis.md
      - Вредносни типови података: prog3/02/05_vrednosni_tipovi.md
      - Конверзије типова: prog3/02/06_konverzije_tipova.md
      - Референтни типови података: prog3/02/07_referentni_tipovi.md
      - Декларација података: prog3/02/08_deklaracija_podataka.md
      - Оператори и изрази: prog3/02/09_operatori_izrazi.md
      - Битски оператори: prog3/02/10_bitski_operatori.md
      - Разгранате структуре: prog3/02/11_razgranata.md
      - Цикличне структуре: prog3/02/12_ciklicna.md
      - Низови: prog3/02/13_nizovi.md
      - Стрингови: prog3/02/14_string.md
      - Листе: prog3/02/15_liste.md
      - Енумерације: prog3/02/16_nabrojivi.md
      - Структуре: prog3/02/17_struct.md
      - Пренос параметара метода по вредности и референци: prog3/02/18_vrednost_referenca.md
      - Преоптерећење метода: prog3/02/19_preopterecenje.md
      - Фајлови и директоријуми: prog3/02/20_fajlovi_direktorijumi.md
      - Рад са текстуалним фајловима: prog3/02/21_file_directory.md
      - Рад са токовима: prog3/02/22_stream.md
      - Рад са бинарним фајловима: prog3/02/23_binary.md
      - Припрема за тест: prog3/02/99_priprema.md
    - Додаци:
      - Unicode карактери: prog3/07/unicode_karakteri.md
      - Прелазне секвенце: prog3/07/prelazne_sekvence.md
      - Приоритет оператора: prog3/07/prioritet_operatora.md
  - Web Design:
    - Добродошли: webd/index.md
    - Увод у веб дизајн:
      - Историјски развој Интернета и веба: webd/01/01_razvoj.md
      - Веб технологије: webd/01/02_tehnologije.md
      - Веб адреса, хостинг и домен: webd/01/03_adresa.md
      - Изглед и функционалност веб сајтова: webd/01/04_izgled.md
      - Задаци за проверу знања: webd/01/05_zadaci.md
    - HTML и CSS:
      - Дескриптивни језици: webd/02/01_deskriptivni_jezici.md
      - Кôд едитори: webd/02/02_kod_editori.md
      - Основни елементи HTML језика: webd/02/03_osnovni_elementi.md
      - Структура HTML странице: webd/02/04_struktura_stranice.md
      - Основни елементи у заглављу: webd/02/05_elementi_head.md
      - Задаци за проверу знања: webd/02/06_zadaci.md
      - Основни елементи у телу: webd/02/07_elementi_body.md
      - Инлајн стилизација елемената: webd/02/08_style.md
      - Форматирање текста: webd/02/09_formatiranje.md
  - UI UX Design:
    - Добродошли: uiux/index.md
    - Увод у UI/UX дизајн:
      - Разлика између UI и UX дизајна: uiux/01/01_uiux.md
      - Значај UI/UX дизајна у дигиталном свету: uiux/01/02_znacaj.md
      - Основни принципи и концепти UI/UX дизајна: uiux/01/03_principi.md
      - Припрема за тест: uiux/01/04_priprema.md
    - Етика и прaксе UI/UX дизајна:
      - Приступачност и инклузивност у дизајну: uiux/02/01_pristupacnost.md
      - Заштита приватности података и транспарентност: uiux/02/02_zastita.md
      - Културни и друштвени фактори у дизајну интерфејса: uiux/02/03_kultura.md
      - Идентификација и превазилажење етичких изазова у UI/UX дизајну: uiux/02/04_prevazilazenje.md
      - Припрема за тест: uiux/02/05_priprema.md
    - Основни принципи UI дизајна:
      - Фонтови: uiux/03/fonts.md
      - Принципи коришћења фонтова: uiux/03/fonts_principles.md
  - Technical Documentation:
    - Добродошли: techdoc/index.md
    - Елементи техничке документација:
      - Шта је техничка документација?: techdoc/01/01_uvod.md
      - Техничка документација и стандарди: techdoc/01/02_standardi.md
      - Техничко писање: techdoc/01/03_pisanje.md
      - Врсте техничко-пословних докумената: techdoc/01/04_vrste.md
      - Кориснички и пројектно оријентисана документација: techdoc/01/05_korisnicki_projektno.md
    - Развој софтверског пројекта:
      - Шта је пројекат: techdoc/02/01_projekat.md
  - Misc:
    - Добродошли: misc/index.md
    - Активација школског Microsoft налога: misc/copilot.md

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - glightbox

hooks:
  - hooks/socialmedia.py

extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/radlovacki
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/velimirradlovacki/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/velimir.radlovacki
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/radlovacki/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/VelimirRadlovački
    - icon: fontawesome/brands/twitter
      link: https://x.com/radlovacki
  generator: false

extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6